### ISSUE TITLE
client.loop.add_signal_handler(getattr(signal, signame),

### ISSUE THREAD

**Issue by MalteBoehm** [badcf00d/nvidia-discord-bot#2]
Logged in as Nvidia Bot#0658
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Projekte\Python\nvidia-discord-bot\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Projekte\Python\nvidia-discord-bot\stock.py", line 79, in on_ready
    client.loop.add_signal_handler(getattr(signal, signame),
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
NotImplementedError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000156A852CE50>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000156A852CE50>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 0

Hey there, i followed your Readme and the bot goes online but i get this error.
Any idea what the issue is?

Thank you

**Comment by badcf00d** [comment]
Huh, interesting, what platform are you running this on? Windows or Linux etc? Looks like it's complaining that it can't add a signal handler for one of sigint or sigterm, or both maybe

**Comment by MalteBoehm** [comment]
Hey there, i´m running it on Windows 11

**Comment by MalteBoehm** [comment]
Solved it, if you want i will create a branch with docker and docker-compose in it. Then everybody can run it

**Comment by badcf00d** [comment]
I think it should be fine to fix the code itself, it looks like a pretty common issue (https://stackoverflow.com/questions/45987985/asyncio-loops-add-signal-handler-in-windows), I run pretty much everything in Linux so I forgot Windows doesn't have signals in the same way.

**Comment by MalteBoehm** [comment]
When i put a try catch arround it it looks like this. 

Might be libcurl  as well? 

ogged in as Nvidia Bot#0658
Welcome message failed: NotImplementedError()
C:\Projekte\Python\nvidia-discord-bot\stock.py:218: RuntimeWarning: coroutine 'send_message' was never awaited
  send_message("Bot Online", "Runeis")
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Loading...
API request failed CalledProcessError(2, ['curl', '-s', 'https://api.store.nvidia.com/partner/v1/feinventory?skus=UK~NVGFT090~NVGFT080T~NVGFT080~NVGFT070T~NVGFT070~NVGFT060T~187&locale=UK', '-H', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0', '-H', 'Accept-Language: en-GB,en-US;q=0.7,en;q=0.3', '--max-time', '10', '--compressed'])
Fail notification failed: UnboundLocalError("local variable 'response' referenced before assignment")
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information
curl: option --compressed: the installed libcurl version doesn't support this
curl: try 'curl --help' for more information
Loading...
API request failed CalledProcessError(2, ['curl', '-s', 'https://api.store.nvidia.com/partner/v1/feinventory?skus=UK~NVGFT090~NVGFT080T~NVGFT080~NVGFT070T~NVGFT070~NVGFT060T~187&locale=UK', '-H', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0', '-H', 'Accept-Language: en-GB,en-US;q=0.7,en;q=0.3', '--max-time', '10', '--compressed'])
Fail notification failed: UnboundLocalError("local variable 'response' referenced before assignment")

**Comment by badcf00d** [comment]
I've fixed the crashes so it will at least run on native Windows, I've just removed the custom signal handler for Windows so it relies on the default discord.py one instead because there's no simple way to have an asynchronous signal handler on Windows, so I wouldn't be able to send a shutting down message anyway. 

Like you mentioned above, the `curl` that ships with windows doesn't support the --compressed flag, so I've just made it use Python Requests when on Windows instead.

If you had already made some Docker files to run it that would be cool to add, if you wanted to make a pull request for those

**Comment by MalteBoehm** [comment]
The Repo is blocked for me. You can add those three files :)
Dockerfile:
```python
FROM python:3.9-slim-bullseye

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .


CMD ["python3", "stock.py"]
```

docker-compose.yml:
```python
version: "3.9"  # optional since v1.27.0
services:
  build-bot:
    restart: always
    build: .
    ports:
      - "3000:3000"
```

README.md
```python
# nvidia-discord-bot
A stock tracker for rtx cards
#### 1. Docker Setup
Install Docker on your system https://docs.docker.com/get-docker/
Install Docker-Compose https://docs.docker.com/compose/install/

#### 2. token.txt
Just a text file with your bot token on the first line

#### 3. channels.txt
 - Uses the format: `<channel id>,<receive debug messages>,<hyphen-seperated list of locales>;`, e.g:
 ```
 123123123123123,true,UK-FR-DE;
 234234234234234,false,UK;
 345345345345345,false,UK-FR;
 ```

#### 4. To start
Open your CMD in the bot folder and type "docker-compose up"

#### 5. To stop
Type "docker-compose down"

```

**Comment by badcf00d** [comment]
Hmm, weird, not sure why you would be blocked from contributing, can't see anything that jumps out to me in the settings :/. But yeh thanks very much for those, I'll get those included at some point soon 👍
